# -*- coding: utf-8 -*-
"""Assignment-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEvuP0YHoAz2_Pit_leRFV6-i3MASlgZ
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

class GaussianNBManual:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.mean = {}
        self.var = {}
        self.priors = {}
        for c in self.classes:
            X_c = X[y == c]
            self.mean[c] = X_c.mean(axis=0)
            self.var[c] = X_c.var(axis=0)
            self.priors[c] = X_c.shape[0] / X.shape[0]

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        posteriors = []
        for c in self.classes:
            prior = np.log(self.priors[c])
            posterior = np.sum(np.log(self._pdf(c, x))) + prior
            posteriors.append(posterior)
        return self.classes[np.argmax(posteriors)]

    def _pdf(self, class_idx, x):
        mean = self.mean[class_idx]
        var = self.var[class_idx]
        numerator = np.exp(- (x - mean) ** 2 / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator

model_manual = GaussianNBManual()
model_manual.fit(X_train, y_train)
y_pred_manual = model_manual.predict(X_test)

print("Manual GaussianNB Accuracy:", accuracy_score(y_test, y_pred_manual))
print("\nClassification Report:\n", classification_report(y_test, y_pred_manual))

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model_builtin = GaussianNB()
model_builtin.fit(X_train, y_train)
y_pred_builtin = model_builtin.predict(X_test)

print("Built-in GaussianNB Accuracy:", accuracy_score(y_test, y_pred_builtin))
print("\nClassification Report:\n", classification_report(y_test, y_pred_builtin))

from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
import numpy as np

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

knn = KNeighborsClassifier()
param_grid = {'n_neighbors': np.arange(1, 21)}

grid = GridSearchCV(knn, param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best K Value:", grid.best_params_)
print("Best Accuracy:", grid.best_score_)